import Head from 'next/head';
import NavBar from './components/NavBar';
import HeroSection from './components/HeroSection';
import Projects from './components/Projects';
import Footer from './components/Footer'; 
import Experiences from './components/Experiences';
import Skills from './components/Skills';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Kenny Cui's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <NavBar />
          <HeroSection />
          <Skills />
          <Experiences />
          <Projects />
        </section>
      </main>
      <Footer />
    </div>
  );
}
